apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-lab7
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /sample/data
    server: 172.17.0.2
