apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lab7
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
