apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab-4
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-lab-4
          image: nginx:1.18
